server:
  port: 8080

spring:
  application:
    name: gic-cinemas-backend

  datasource:
    url: jdbc:h2:mem:cinemasdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update       # auto-create/update tables from @Entity classes
    show-sql: true           # show SQL statements in logs
    properties:
      hibernate:
        format_sql: true     # nicely format the printed SQL

  h2:
    console:
      enabled: true
      path: /h2-console      # view at http://localhost:8080/h2-console
